package com.example.rag.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO representing a single recommendation item from LLM response
 * Used for parsing JSON response from OpenAI
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class LlmRecommendationItem {

    /**
     * Product ID from the product catalog
     */
    @JsonProperty("id")
    private String id;

    /**
     * Product name as returned by LLM
     */
    @JsonProperty("name")
    private String name;

    /**
     * Recommendation reason (max 50 Chinese characters)
     * Generated by LLM based on user query and product features
     */
    @JsonProperty("reason")
    private String reason;
}
